"""empty message

Revision ID: 910cf40d39ed
Revises: 3ff4d704169d
Create Date: 2023-01-03 13:00:23.232069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910cf40d39ed'
down_revision = '3ff4d704169d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('files', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.BLOB(), nullable=True))
        batch_op.drop_column('files')

    # ### end Alembic commands ###
